package com.adobe.custom.connect.connect_url_shortner.components.impl.servlets;

import org.apache.felix.scr.annotations.sling.SlingServlet;
import org.apache.sling.api.SlingHttpServletRequest;
import org.apache.sling.api.SlingHttpServletResponse;
import org.apache.sling.api.resource.Resource;
import org.apache.sling.api.servlets.SlingAllMethodsServlet;
import org.apache.sling.api.servlets.SlingSafeMethodsServlet;

import javax.servlet.ServletException;
import java.io.IOException;

/**
 * Servlet that writes some sample content into the response. It is mounted for
 * all resources of a specific Sling resource type. The
 * {@link SlingSafeMethodsServlet} shall be used for HTTP methods that are
 * idempotent. For write operations use the {@link SlingAllMethodsServlet}.
 */
@SlingServlet(resourceTypes = "myproject/pages/homepage")
public class SimpleServlet extends SlingSafeMethodsServlet {

	@Override
	protected void doGet(SlingHttpServletRequest req,
			SlingHttpServletResponse resp) throws ServletException, IOException {
		Resource resource = req.getResource();
		resp.getOutputStream().println(resource.toString());
		resp.getOutputStream().println(
				"This content is generated by the SimpleServlet");
	}
}